
CREATE SEQUENCE IF NOT EXISTS SQ_PRODUCT
    START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TB_PRODUCT (
    id BIGINT NOT NULL DEFAULT nextval('SQ_PRODUCT'),
    name_product VARCHAR(100) NOT NULL,
    price_product NUMERIC(10, 2) NOT NULL CHECK (price_product >= 0),
    stock_product INTEGER NOT NULL DEFAULT 0 CHECK (stock_product >= 0),

    CONSTRAINT PK_ID_PRODUCT PRIMARY KEY (id)
);
