
CREATE SEQUENCE IF NOT EXISTS SQ_CLIENT
    START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TB_CLIENT (
    id BIGINT NOT NULL DEFAULT nextval('SQ_CLIENT'),
    name_client VARCHAR(50) NOT NULL,
    cpf_client VARCHAR(11) NOT NULL,
    contact_client VARCHAR(50) NOT NULL,

    CONSTRAINT PK_ID_CLIENT PRIMARY KEY (id),
    CONSTRAINT UK_CPF_CLIENT UNIQUE (cpf_client)
);
